language: python
python:
        - "3.6"
sudo: required
services:
        - docker
branches:
        only:
                - develop
                - master
before_install:
        - pip install -r requirements-travis.txt

script:
        - set -e
        - export PYTHONPATH="${PYTHONPATH}:${PWD}"
        - printenv
        - py.test -sv tests
        - docker build -t ptmn/devopshqissues .
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker push ptmn/devopshqissues
        - if [ $TRAVIS_BRANCH = "develop" ]; then echo "DEV deploy"; fi
        - if [ $TRAVIS_BRANCH = "master" ]; then echo "PROD deploy"; fi
