language: python
python:
        - "3.6"
sudo: required
services:
        - docker
branches:
        only:
                - develop
                - master
before_install:
        - pip install -r requirements-travis.txt
jobs:
  include:
    - stage: "Test"
      script: python setup.py pytest
    - stage: "Build"
      script:
        - python setup.py bdist_wheel
        - docker build -t ptmn/devopshqissues .
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker push ptmn/devopshqissues
