language: python
python:
        - "3.6"
sudo: required
services:
        - docker
branches:
        only:
                - develop
                - master
                - travisconf
before_install:
        - pip install -r requirements-travis.txt

script:
  - printenv
  - set -e
  - python setup.py pytest
  - python setup.py bdist_wheel
  - docker build -t ptmn/devopshqissues .

deploy:
  - provider: script
    script:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker push ptmn/devopshqissues:dev
    on:
      branch: develop
    skip_cleanup: true
  - provider: script
    script:
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker push ptmn/devopshqissues
    on:
      branch: master
    skip_cleanup: true
  - provider: script
    script:
      - ls
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker push ptmn/devopshqissues
    on:
      branch: travisconf
