language: python
python:
        - "3.6"
sudo: required
services:
        - docker
branches:
        only:
                - develop
                - master
                - travisconf
before_install:
        - pip install -r requirements-travis.txt

script:
  - printenv
  - set -e
  - python setup.py pytest
  - python setup.py bdist_wheel
  - docker build -t ptmn/devopshqissues .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push ptmn/devopshqissues
