language: python
os: linux

python:
    - "3.6"

services:
    - docker

branches:
    only:
        - develop
        - master

before_install:
    - python -m pip install --upgrade pip

script:
    - printenv
    - set -e
    - python setup.py pytest
    - python setup.py bdist_wheel
    - docker build -t ptmn/devopshqissues .

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push ptmn/devopshqissues
